### ISSUE TITLE
remote-ls: this.registry.replace is not a function

### ISSUE THREAD

**Issue by luii** [piranna/coverdeeps#1]
If i run coverdeeps on the project or any other project i get this error

[philipp@arch nodeos-mount-utils]$ coverdeeps
/home/philipp/.nvm/versions/node/v4.4.2/lib/node_modules/coverdeeps/node_modules/npm-remote-ls/lib/remote-ls.js:32
  request.get(this.registry.replace(/\/$/, '') + '/' + task.name, {json: true},
                            ^

TypeError: this.registry.replace is not a function
    at RemoteLS._loadPackageJson (/home/philipp/.nvm/versions/node/v4.4.2/lib/node_modules/coverdeeps/node_modules/npm-remote-ls/lib/remote-ls.js:32:29)
    at /home/philipp/.nvm/versions/node/v4.4.2/lib/node_modules/coverdeeps/node_modules/npm-remote-ls/lib/remote-ls.js:21:13
    at /home/philipp/.nvm/versions/node/v4.4.2/lib/node_modules/coverdeeps/node_modules/async/dist/async.js:3496:13
    at q.process (/home/philipp/.nvm/versions/node/v4.4.2/lib/node_modules/coverdeeps/node_modules/async/dist/async.js:3095:21)
    at Immediate._onImmediate (/home/philipp/.nvm/versions/node/v4.4.2/lib/node_modules/coverdeeps/node_modules/async/dist/async.js:2988:16)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by piranna** [comment]
'registry' module is giving some semver problems, what one are you using?

**Comment by luii** [comment]
I just installed coverdeeps globaly and got this problem, should i install a registry?

**Comment by piranna** [comment]
> I just installed coverdeeps globaly and got this problem, should i install a registry?

No, i'm talking about the [registry-url](https://www.npmjs.com/package/registry-url) module.
